name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install valgrind
        run: sudo apt-get -y install valgrind
      
      - name: Configure Cmake
        run: cmake -S . -B build
      
      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd ./build
          ls -al
          ctest

      - name: Memory Leak Check
        run: |
          cd ./build
          ls -al
          valgrind --leak-check=yes ./miniJSON_tests
